### ISSUE TITLE
Email notification - Controls required on account page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/design-gc-digital-talent#42]
### User story
As a user receiving notification emails, I want a place where I can turn off the notifications, so I can stop the spam.

### Details
The idea is to build a minimal UI in the user profile (or account settings) that will allow them to turn off email notifications if they want. This should be built so that on-platform or on-device notification controls can be added in later. We should also build this with the idea that there will be many different nonfictions added over time.

**Comment by gobyrne** [comment]
IMO we don't strictly need this before we release our first email notification, but if we can keep the level of effort low, it might be worth waiting for.

**Comment by substrae** [comment]
@gobyrne this is part of a larger UI piece for notifications that we shouldn't be designing in isolation. We should properly design this UI holistically if the requirement is there to enable notifications, even if they're only email to start.

**Comment by gobyrne** [comment]
@substrae 
You know me, I'm keen to build it iteratively. If we keep it basic for the first pass, the devs will figure out the functionality and it will be easy to move it elsewhere in future iterations. So your call @substrae if you want a basic UI for turning off our first notification (24 hours left to apply) or if we roll it out without a way to turn it off (understanding that we will build it out holistically in the future).

My preference is definitely something simple as a first pass so that dev figure out how to do it early. I just need force some movement on notifications, they have been languishing for too long. And I don't think we can afford to make the holistic UI a priority for you right now. Happy to discuss though.

**Comment by substrae** [comment]
@gobyrne 

My concern lies with us building this once quickly without properly thinking through the mechanics and breadth of the types of controls we need and where they should exist. Beyond that, it's bad form to build a feature in a particular spot and then move it shortly afterwards, because it's going to confuse folks. At a bare minimum, we should be thinking about where these controls need to go on the profile and how the UI will scale, even if we don't build out the full thing yet.
